# Generated by Django 3.1.1 on 2020-09-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avatar', models.URLField()),
                ('country_of_birth', models.CharField(max_length=100)),
                ('place_of_birth', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('job', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=255)),
                ('political_party', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
