# Generated by Django 3.1.1 on 2020-09-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
